src/MyCommerce.App/ViewModels/ProductViewModel.cs
using Microsoft.AspNetCore.Http;
using MyCommerce.App.Extensions;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyCommerce.App.ViewModels
{
    public class ProductViewModel
    {
        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage ="O campo {0} é obrigatório")]
        [DisplayName("Fornecedor")]
        public Guid ProviderId { get; set; }

        [DisplayName("Nome")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(200, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
        public string Name { get; set; }

        [DisplayName("Descrição")]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(1000, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
        public string Description { get; set; }        
        public string Image { get; set; }

        [NotMappedAttribute]
        [DisplayName("Imagem do Produto")]
        public IFormFile ImageUpload { get; set; }

        [DisplayName("Preço")]
        [Coin]
        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        public decimal Price { get; set; }

        [DisplayName("Data de Cadastro")]
        [ScaffoldColumn(false)]        
        public DateTime RegisterDate { get; set; }

        [DisplayName("Ativo?")]
        public bool Active { get; set; }

        [DisplayName("Fornecedor")]
        public ProviderViewModel Provider { get; set; }

        public IEnumerable<ProviderViewModel> Providers { get; set; }
    }
}

src/MyCommerce.App/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyCommerce.App.Extensions;
using MyCommerce.App.ViewModels;
using MyCommerce.Business.Interfaces;
using MyCommerce.Business.Models;
using MyCommerce.Business.Notifications;

namespace MyCommerce.App.Controllers
{
    [Authorize]
    public class ProductsController : BaseController
    {
        private readonly IProductRepository _productRepository;
        private readonly IProviderRepository _providerRepository;
        private readonly IProductService _productService;
        private readonly IMapper _mapper;

        public ProductsController(IProductRepository productRepository, IProductService productService, 
            IProviderRepository providerRepository, IMapper mapper, INotificator notificator) : base(notificator)
        {
            _productRepository = productRepository;
            _providerRepository = providerRepository;
            _mapper = mapper;
            _productService = productService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<ProductViewModel>>(await _productRepository.GetProductsWithProviders()));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(Guid id)
        {
            var productViewModel = await GetProduct(id);
            if (productViewModel == null)
                return NotFound();

            return View(productViewModel);
        }

        [ClaimsAuthorize("Product", "Add")]
        public async Task<IActionResult> Create()
        {
            var productViewModel = await PopulateProviders(new ProductViewModel());
            return View(productViewModel);
        }

        [HttpPost]
        [ClaimsAuthorize("Product", "Add")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductViewModel productViewModel)
        {
            productViewModel = await PopulateProviders(productViewModel);

            if (!ModelState.IsValid) 
                return View(productViewModel);

            string imagePrefix = Guid.NewGuid() + "_";
            if (!await UploadFile(productViewModel.ImageUpload, imagePrefix))
                return View(productViewModel);

            productViewModel.Image = imagePrefix + productViewModel.ImageUpload.FileName;
            
            await _productService.Add(_mapper.Map<Product>(productViewModel));
            if (!ValidOperation())
                return View(productViewModel);

            return RedirectToAction("Index");
        }

        [ClaimsAuthorize("Product", "Edit")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var productViewModel = await GetProduct(id);
            if (productViewModel == null)
                return NotFound();

            return View(productViewModel);
        }

        [ClaimsAuthorize("Product", "Edit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, ProductViewModel productViewModel)
        {
            if (id != productViewModel.Id)
                return NotFound();

            var productUpdated = await GetProduct(id);
            productViewModel.Provider = productUpdated.Provider;
            productViewModel.Image = productUpdated.Image;

            if (!ModelState.IsValid)
                return View(productViewModel);

            if (productViewModel.ImageUpload != null)
            {
                var imagePrefix = Guid.NewGuid() + "_";
                if (!await UploadFile(productViewModel.ImageUpload, imagePrefix))
                    return View(productViewModel);

                productUpdated.Image = imagePrefix + productViewModel.ImageUpload.FileName;
            }

            await _productService.Update(_mapper.Map<Product>(productViewModel));
            if (!ValidOperation())
                return View(productViewModel);
            return RedirectToAction(nameof(Index));
        }

        [ClaimsAuthorize("Product", "Remove")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var product = await GetProduct(id);
            if (product == null)
                return NotFound();

            return View(product);
        }

        [ClaimsAuthorize("Product", "Remove")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var product = await GetProduct(id);
            if (product == null)
                return NotFound();

            await _productService.Remove(id);
            if (!ValidOperation())
                return View(product);

            TempData["Sucess"] = "Produto excluído com sucesso!";
            return RedirectToAction(nameof(Index));
        }

        private async Task<ProductViewModel> GetProduct(Guid productId)
        {
            var product = _mapper.Map<ProductViewModel>(await _productRepository.GetProductWithProvider(productId));
            product.Providers = _mapper.Map<IEnumerable<ProviderViewModel>>(await _providerRepository.GetAll());

            return product;
        }

        private async Task<ProductViewModel> PopulateProviders(ProductViewModel product)
        {
            product.Providers = _mapper.Map<IEnumerable<ProviderViewModel>>(await _providerRepository.GetAll());

            return product;
        }

        private async Task<bool> UploadFile(IFormFile file, string imagePrefix)
        {
            if (file.Length <= 0)
                return false;

            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", imagePrefix + file.FileName);

            if (System.IO.File.Exists(path))
            {
                ModelState.AddModelError(string.Empty, "Já existe um arquivo com este nome!");
                return false;
            }

            using (var stream = new FileStream(path, FileMode.Create))
                await file.CopyToAsync(stream);
            
            return true;
        }
    }
}

src/MyCommerce.App/Utils/ViewComponents/SummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyCommerce.Business.Notifications;
using System.Threading.Tasks;

namespace MyCommerce.App.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly INotificator _notificator;
        public SummaryViewComponent(INotificator notificator)
        {
            _notificator = notificator;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notifications = await Task.FromResult(_notificator.GetNotifications());
            notifications.ForEach(n => ViewData.ModelState.AddModelError(string.Empty, n.Message));
            return View();
        }
    }
}

src/MyCommerce.App/Views/Products/Create.cshtml
@model MyCommerce.App.ViewModels.ProductViewModel

@{
    ViewData["Title"] = "Produto";
}

<h3 style="padding-top: 50px">@ViewData["Title"] </h3>

<hr />
<div class="row">
    <div class="col-md-5">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
              <label asp-for="ProviderId" class="control-label"></label>
              <select asp-for="ProviderId" class="form-control" asp-items="@(new SelectList(Model.Providers, "Id", "Name"))">
                <option></option>
              </select>
              <span asp-validation-for="ProviderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea cols="40" rows="5" asp-for="Description" class="form-control" ></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUpload" class="control-label"></label>
                <div class="custom-file">
                  <input type="file" class="custom-file-input" id="ImageUpload" asp-for="ImageUpload" />
                  <label data-browse="Procurar" class="custom-file-label" for="ImageUpload"></label>
                  <label style="display: none" id="img_name"></label>
                </div>
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
              <input type="submit" value="Cadastrar" class="btn btn-success" />
              <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

  <script>
    $("#ImageUpload").change(function () {
      $("#img_name").text(this.files[0].name);
      $("img_name")[0].style.display = 'block';
    });

    $("#ImageUpload").attr("data-val", "true");
    $("ImageUpload").attr("data-val-required", "Preencha o campo imagem");
  </script>
}

src/MyCommerce.App/Views/Products/Delete.cshtml
@model MyCommerce.App.ViewModels.ProductViewModel

@{
    ViewData["Title"] = "Exclur " + Model.Name;
}

<h4 style="padding-top: 50px">@ViewData["Title"]</h4>

<h5>Você tem certeza disso?</h5>
<div>
  <div class="col-md-4">
    <img src="~/img/@Model.Image" alt="@Model.Image" style="width: 300px; height: 428px" />
  </div>
  <div class="col-md-6">
    <dl>
      <dt>
        @Html.DisplayNameFor(model => model.Name)
      </dt>
      <dd>
        @Html.DisplayFor(model => model.Name)
      </dd>
      <dt>
        @Html.DisplayNameFor(model => model.Description)
      </dt>
      <dd>
        @Html.DisplayFor(model => model.Description)
      </dd>
      <dt>
        @Html.DisplayNameFor(model => model.Price)
      </dt>
      <dd>
        @model.Price.ToString("C")
      </dd>
      <dt>
        @Html.DisplayNameFor(model => model.RegisterDate)
      </dt>
      <dd>
        @Html.DisplayFor(model => model.RegisterDate)
      </dd>
      <dt>
        @Html.DisplayNameFor(model => model.Active)
      </dt>
      <dd>
        @Html.DisplayFor(model => model.Active)
      </dd>
    </dl>
  </div>

  <div>
    <form asp-action="Delete">
      <input type="hidden" asp-for="Id" />
      <input type="submit" value="Excluir" class="btn btn-danger" /> |
      <a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
    </form>
  </div>
</div>

src/MyCommerce.App/Views/Products/Details.cshtml
@model MyCommerce.App.ViewModels.ProductViewModel

@{
  ViewData["Title"] = "Detalhes do Produto - " + Model.Name;
}

<h4 style="padding-top: 50px">@ViewData["Title"]</h4>
<hr />
<div class="row">
  <div class="col-md-4">
    <img src="~/img/@Model.Image" alt="@Model.Image" style="width: 300px; height: 428px"/>
  </div>
  <div class="col-md-6">
    <dl>
      <dt>
        @Html.DisplayNameFor(model => model.Name)
      </dt>
      <dd>
        @Html.DisplayFor(model => model.Name)
      </dd>
      <dt>
        @Html.DisplayNameFor(model => model.Description)
      </dt>
      <dd>
        @Html.DisplayFor(model => model.Description)
      </dd>
      <dt>
        @Html.DisplayNameFor(model => model.Price)
      </dt>
      <dd>
        @model => model.Price.ToString("C")
      </dd>
      <dt>
        @Html.DisplayNameFor(model => model.RegisterDate)
      </dt>
      <dd>
        @Html.DisplayFor(model => model.RegisterDate)
      </dd>
      <dt>
        @Html.DisplayNameFor(model => model.Active)
      </dt>
      <dd>
        @Html.DisplayFor(model => model.Active)
      </dd>
    </dl>
    <div>
      <a class="btn btn-dark" asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
      <a class="btn btn-info" href="javascript:window.history.back()">Voltar</a>
    </div>
  </div>
</div>

src/MyCommerce.App/Views/Products/Edit.cshtml
@model MyCommerce.App.ViewModels.ProductViewModel

@{
  ViewData["Title"] = "Editar" + Model.Name;
}

<h3 style="padding-top: 50px">@ViewData["Title"] </h3>
<hr />
<div class="row">
  <div class="col-md-5">
    <form enctype="multipart/form-data" asp-action="Edit">
      <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      <input type="hidden" asp-for="Id" />

      <div class="form-group">
        <label asp-for="ProviderId" class="control-label"></label>
        <label><b>@Model.Provider.Name</b></label>
      </div>

      <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea cols="40" rows="5" asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label class="control-label">Imagem Atual</label><br />
        <img src="~/img/@Model.Image" alt="@Model.Image" style="width: 70px; height: 100px" />
      </div>
      <div class="form-group">
        <label asp-for="ImageUpload" class="control-label"></label>
        <div class="custom-file">
          <input type="file" class="custom-file-input" id="ImageUpload" asp-for="ImageUpload" />
          <label data-browse="Procurar" class="custom-file-label" for="ImageUpload"></label>
          <label style="display: none" id="img_name"></label>
        </div>
        <span asp-validation-for="Image" class="text-danger"></span>
      </div>
      <div class="form-group">
        <label asp-for="Price" class="control-label"></label>
        <input asp-for="Price" class="form-control" />
        <span asp-validation-for="Price" class="text-danger"></span>
      </div>
      <div class="form-group form-check">
        <label class="form-check-label">
          <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
        </label>
      </div>
      <div class="form-group">
        <input type="submit" value="Salvar" class="btn btn-success" />
        <a class="btn btn-info" href="javascript:window.history.back()">Voltar</a>
      </div>
    </form>
  </div>
</div>


@section Scripts {
  @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
  <script>
    $("#ImageUpload").change(function () {
      $("#img_name").text(this.files[0].name);
      $("img_name")[0].style.display = 'block';
    });
  </script>
}

src/MyCommerce.App/Views/Products/Index.cshtml
@model IEnumerable<MyCommerce.App.ViewModels.ProductViewModel>

@{
    ViewData["Title"] = "Produtos";
}

<h2>@ViewData["Title"]</h2>
<vc:summary></vc:summary>
<p>
  <a class="btn btn-primary" asp-action="Create">Cadastrar Produto</a>
</p>
<partial name="_ProductsList" />

src/MyCommerce.App/Views/Products/_ProductsList.cshtml
@model IEnumerable<MyCommerce.App.ViewModels.ProductViewModel>

@{
    ViewData["Title"] = "Produtos";
}

<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th></th>
      <th>
        @Html.DisplayNameFor(model => model.Name)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Provider)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Price)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Active)
      </th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    @foreach (var item in Model)
    {
    <tr>
      <td>
        <img src="~/img/@item.Image" alt="@item.Image" style="width: 70px; height: 100px" />
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Name)
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Provider.Name)
      </td>
      <td>
        @item.Price.ToString("C")
      </td>
      <td>
        @Html.DisplayFor(modelItem => item.Active)
      </td>

      <td class="text-right">
        <a class="btn btn-info" asp-controller="Products" asp-action="Details" asp-route-id="@item.Id"><spam class="fa fa-search"></spam></a>
        <a class="btn btn-dark" asp-controller="Products" asp-action="Edit" asp-route-id="@item.Id"><spam class="fa fa-pencil-alt"></spam></a>
        <a class="btn btn-danger" asp-controller="Products" asp-action="Delete" asp-route-id="@item.Id"><spam class="fa fa-trash"></spam></a>
      </td>
    </tr>
    }
  </tbody>
</table>